# http://localhost:3000/

# http://localhost:3000/profile/20

POST http://localhost:3000/signin
Content-Type: application/json

{
  "email": "jude@gmail.com",
  "password": "duke"
}

# POST http://localhost:3000/register
# Content-Type: application/json

# {
#   "email": "jude@gmail.com",
#   "password": "duncan",
#   "name": "Jude"
# }

# PUT http://localhost:3000/image
# Content-Type: application/json

# {
#   "id": "8"
# }